### ISSUE TITLE
does not work in blender 2.79

### ISSUE THREAD

**Issue by xboxcopy** [bblanimation/interactive-physics-editor#10]
the addon shows up in blender 2.79. when I click "new interactive physics session" it gives an error.
below are the report

Description of the Problem:

Blender Version: 002.079.000
Addon Version: 1, 1, 2
Platform Info:
   system   = Windows
   platform = Windows-10-10.0.18362
   version  = 10.0.18362
   python   = 3.5.3
Error:
EXCEPTION (<class 'AttributeError'>): 'Scene' object has no attribute 'collection'
         C:\Users\U\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\interactive_physics_editor_1_1_2\operators\setup_phys.py
000 0046:modal() for obj in context.scene.collection.all_objects:

**Comment by bblanimation** [comment]
Thank you for bringing this to my attention! This bug has been fixed in commit 6c7137a, and will be published when Blender 2.81 is released to the public.
